### ISSUE TITLE
S Message: Date Until month parsing wrong?

### ISSUE THREAD

**Issue by spinscale** [Bouni/max-cube-protocol#30]
While testing against my cube I noticed that parsing the month of a date seems of. My cube responded to a holiday setting with this datetime payload response (as ints) 

```[29, 145, 3]```

which was equivalent to 2017-Jan-29 1:30

This means, that the [explanation](https://github.com/Bouni/max-cube-protocol/blame/master/S-Message.md#L103-L108) is wrong by one bit for the month.

It might be just my cube and its age/firmware, but I figured it's worth asking.

**Comment by marcelrv** [comment]
No, you are right, the picture is wrong.
picture is pointing to the 7th bit for the month, but it should be the 8th bit.
