### ISSUE TITLE
Cube loosing its config

### ISSUE THREAD

**Issue by asantaga** [Bouni/max-cube-protocol#42]
Hi all,

Ive been running homeassistant and some python code (piheating) and its been working fab, BUT Ive noticed recently that since running the code I regularly see the cube die and loose all its config.

Doing some R&D i think its because we're polling the CUBE too much and wondered if this is just hearsay or theres some evidence around this..

Anyone else seen it?

**Comment by marcelrv** [comment]
This is a common issue.
E.g. see https://community.openhab.org/t/max-cube-loses-all-settings-with-openhab/8537

Exact issue cause is unknown

**Comment by asantaga** [comment]
From reading the thread it would appear reducing the poll rate may help..

i'll admit until I used HomeAssistant (with the max bindings) and my homebrew boiler controller I never had a problem.. Im going to reduce my polling to 5mins for the boiler controller and 13 mins for HomeAssistant , this way they never clash...

Is it possible to programatically add devices without clicking the teachIn button again??

Im thinking we could detect the corruption and then automagically reset all the data in the cube?

**Comment by asantaga** [comment]
guys, 

Just as FYI, I have two devices polling the cube. One at 5mins and HA at 13mins.. After one month of constant polling the cube lost its config.. 

Im now trying 15 & 30mins to see what happens.. An alternative is to write something else which will poll the devices ONCE and then let others read it from this cache.. but that would them make it incompatible with other projects.. ...

**Comment by asantaga** [comment]
Closing issue as I havent found a solution and moving to a different product.. Shame
