### ISSUE TITLE
s command temperature and time of day

### ISSUE THREAD

**Issue by pacostiro** [Bouni/max-cube-protocol#9]
Hi!

I am writing a small application that implements some of the messages in order to read the configuration of the cube and devices and to set some of them. I am most interested in setting the weekly program.
While testing it I noticed that your description for the two fields, temperature and time of day, is not accurate.
"Unlike 'temperature & mode' it seams the value must be divided by 4 to get the actual temperature"
Actually the 7 MSB from the temperature field represents temperature in Celsius \* 2 while the least significant bit together with the Time of day field multiplied by 5 describe the time of the day in minutes.

It is also explicable because 24h is codded with 288 > 256. A byte is not enough to reach the highest value, 9 bits are actually used.

Regards,
Costin

**Comment by Bouni** [comment]
Hi Costin,

I've not worked on this project for a long time. Please send me a pull request with your changes. That would be very nice!
